# Generated by Django 4.2.3 on 2023-09-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_account_id_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='account_id',
        ),
    ]
