# Generated by Django 4.2.3 on 2023-09-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_user_userprofile_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='account_id',
            new_name='user',
        ),
    ]
