version: '3'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - '8000:8000'
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cars_db
    ports:
      - '5454:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
