import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE","cars_api.settings"),
django.setup(),

from cars.models import CarModel

car_model_data = [
{'make':'Audi', 'model':'A1'},
{'make':'Audi', 'model':'A2'},
{'make':'Audi', 'model':'A3'},
{'make':'Audi', 'model':'A4'},
{'make':'Audi', 'model':'A5'},
{'make':'Audi', 'model':'A6'},
{'make':'Audi', 'model':'A8'},
{'make':'BMW', 'model':'1er'},
{'make':'BMW', 'model':'3er'},
{'make':'BMW', 'model':'5er'},
{'make':'BMW', 'model':'6er'},
{'make':'BMW', 'model':'7er'},
{'make':'BMW', 'model':'z4'},
{'make':'BMW', 'model':'X3'},
{'make':'BMW', 'model':'X5'},
{'make':'BMW', 'model':'X6'},
{'make':'Citroen', 'model':'C1'},
{'make':'Citroen', 'model':'C2'},
{'make':'Citroen', 'model':'C3'},
{'make':'Citroen', 'model':'C4'},
{'make':'Citroen', 'model':'C4 Picasso'},
{'make':'Citroen', 'model':'C5'},
{'make':'Citroen', 'model':'C6'},
{'make':'Daewoo', 'model':'Nexia'},
{'make':'Daewoo', 'model':'Espero'},
{'make':'Daewoo', 'model':'Nubira'},
{'make':'Daewoo', 'model':'Matiz'},
{'make':'Eagle', 'model':'Wagon'},
{'make':'Eagle', 'model':'Talon'},
{'make':'Ford', 'model':'Focus'},
{'make':'Ford', 'model':'Mondeo'},
{'make':'Ford', 'model':'Fusion'},
{'make':'Ford', 'model':'C-Max'},
{'make':'Ford', 'model':'S-Max'},
{'make':'GMC', 'model':'Yukon'},
{'make':'GMC', 'model':'Suburban'},
{'make':'Hummer', 'model':'H3'},
{'make':'Hummer', 'model':'H2'},
{'make':'Hummer', 'model':'H1'},
{'make':'Infiniti', 'model':'QX4'},
{'make':'Infiniti', 'model':'G37'},
{'make':'Jeep', 'model':'Wrangler'},
{'make':'Jeep', 'model':'Compass'},
{'make':'Jeep', 'model':'Liberty'},
{'make':'KIA', 'model':'Sportage'},
{'make':'KIA', 'model':'Sorento'},
{'make':'KIA', 'model':'Seed'},
{'make':'KIA', 'model':'Cerato'},
{'make':'KIA', 'model':'Magentis'},
{'make':'Lincoln', 'model':'Navigator'},
{'make':'Lincoln', 'model':'Towncar'},
{'make':'Mercedes Benz', 'model':'S klasse'},
{'make':'Mercedes Benz', 'model':'C klasse'},
{'make':'Mercedes Benz', 'model':'A klasse'},
{'make':'Nissan', 'model':'Almera'},
{'make':'Nissan', 'model':'Skyline'},
{'make':'Nissan', 'model':'GT-R'},
{'make':'Nissan', 'model':'Murano'},
{'make':'Nissan', 'model':'Patrol'},
{'make':'Nissan', 'model':'Maxima'},
{'make':'Opel', 'model':'Corsa'},
{'make':'Opel', 'model':'Insignia'},
{'make':'Opel', 'model':'Astra'},
{'make':'Peugeot', 'model':'208'},
{'make':'Peugeot', 'model':'308'},
{'make':'Peugeot', 'model':'307'},
{'make':'Peugeot', 'model':'407'},
{'make':'Peugeot', 'model':'508'},
{'make':'Renault', 'model':'Laguna'},
{'make':'Renault', 'model':'Clio'},
{'make':'Renault', 'model':'Symbol'},
{'make':'Renault', 'model':'Logan'},
{'make':'Skoda', 'model':'Octavia'},
{'make':'Skoda', 'model':'Fabia'},
{'make':'Skoda', 'model':'Superb'},
{'make':'Skoda', 'model':'Yeti'},
{'make':'Toyota', 'model':'Corolla'},
{'make':'Toyota', 'model':'Camry'},
{'make':'Toyota', 'model':'Land Cruiser'},
{'make':'Toyota', 'model':'Yaris'},
{'make':'Toyota', 'model':'Auris'},
{'make':'Toyota', 'model':'Prius'},
{'make':'Toyota', 'model':'RAV4'},
{'make':'UAZ', 'model':'Patriot'},
{'make':'Volvo', 'model':'S80'},
{'make':'Volvo', 'model':'S60'},
{'make':'Volvo', 'model':'S50'},
{'make':'Volvo', 'model':'XC70'},
{'make':'Volvo', 'model':'XC90'},
{'make':'Volkswagen', 'model':'Golf'},
{'make':'Volkswagen', 'model':'Passat'},
{'make':'Volkswagen', 'model':'Phaeton'},
{'make':'Volkswagen', 'model':'Tuareg'},
{'make':'Volkswagen', 'model':'Scirocco'},
{'make':'Ferrari', 'model':'458 Italia'},
{'make':'Ferrari', 'model':'458 Spider'},
{'make':'Fiat', 'model':'Panda'},
{'make':'Fiat', 'model':'500'},
{'make':'Alfa Romeo', 'model':'Mito'}
]
    
for data in car_model_data:
    CarModel.objects.create(**data),

print("CarModels has been successfully added to the database!")