# Generated by Django 4.2.3 on 2023-09-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_number_of_doors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='car',
        ),
    ]
