# Generated by Django 4.2.3 on 2023-09-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_advertisement_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
